### ISSUE TITLE
under this education section, I think it would be better to change "physical stream" into "science stream"

### ISSUE THREAD

**Issue by Abiramy-R** [arshedgithub/my-resume#9]
![image](https://user-images.githubusercontent.com/94125348/150052429-ba139f90-9f9e-4451-99f5-1c9d7dac5d51.png)

**Comment by arshedgithub** [comment]
Maths stream is called physical stream and Bio stream is called science stream.
Isn't it ?

**Comment by Abiramy-R** [comment]
oops! 
yeah, u r right.  I think I got that wrong. it's my mistake.
sorry for the wrong issue.
